### ISSUE TITLE
fabio 1.2rc3 panics with -v

### ISSUE THREAD

**Issue by magiconair** [eBay/fabio#128]
```
$ fabio -v
2016/07/13 09:25:09 [INFO] Runtime config
null
2016/07/13 09:25:09 [INFO] Version 1.2rc3 starting
2016/07/13 09:25:09 [INFO] Go runtime is go1.6.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bd8]

goroutine 1 [running]:
panic(0x4bfcc0, 0xc82000e0d0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
main.initRuntime(0x0)
	/private/tmp/fabio-20160713-7624-1qyqjmx/fabio-1.2rc3/src/github.com/eBay/fabio/main.go:92 +0x5c8
main.main()
	/private/tmp/fabio-20160713-7624-1qyqjmx/fabio-1.2rc3/src/github.com/eBay/fabio/main.go:43 +0x43b
```

Forgot an edge case when parsing the configuration

**Comment by magiconair** [comment]
Fixed in 1.2rc4
